import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { authService } from '../services/auth';
import { useAuth } from './AuthContext';

export type AppLanguage = 'en' | 'fr';

type Dictionary = Record<string, string>;

const dictionaries: Record<AppLanguage, Dictionary> = {
  en: {
    settings: 'Settings',
    home: 'Home',
    messaging: 'Messaging',
    store: 'Store',
    dashboard: 'Dashboard',
    menu: 'Menu',
    account: 'Account',
    preferences: 'Preferences',
    support_legal: 'Support & Legal',
    language: 'Language',
    theme: 'Theme',
    help_center: 'Help Center',
    choose_language: 'Choose your preferred language',
    english: 'English',
    french: 'Français',
    save_changes: 'Save Changes',
    confirm_booking: 'Confirm Booking',
    update_personal_info: 'Update your personal information',
    manage_addresses: 'Manage Addresses',
    add_edit_locations: 'Add or edit your saved locations',
    payment_methods: 'Payment Methods',
    manage_payment_options: 'Manage your payment options',
    choose_app_appearance: 'Choose your app appearance',
    help_privacy_terms_about: 'Help, Privacy, Terms, About',
    select_date: 'Select a date',
    back: 'Back',
    is_coming_soon: 'is coming soon',
    we_are_working_to_bring: 'We are working hard to bring',
    to_you_stay_tuned: 'to you. Stay tuned!',
    close: 'Close',
    search_placeholder: 'Search for car wash services…',
    book_now: 'Book Now',
    book: 'Book',
    km_away: 'km away',
    location_permission: 'Location Permission',
    permission_denied_msg: 'Permission denied. Using default city center.',
    profile: 'Profile',
    welcome_guest: 'Welcome, Guest!\n',
    guest_prompt: 'Sign in or create an account to access your profile and booking history',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    service_provider: 'Service Provider',
    customer: 'Customer',
    member_since: 'Member since',
    your_stats: 'Your Stats',
    rating_label: 'Rating',
    jobs_done: 'Jobs Done',
    contact_information: 'Contact Information',
    email: 'Email',
    phone: 'Phone',
    location: 'Location',
    account_label: 'Account',
    change_password: 'Change Password',
    worker_dashboard: 'Worker Dashboard',
    sign_out: 'Sign Out',
    sign_out_confirm_title: 'Sign Out',
    sign_out_confirm_message: 'Are you sure you want to sign out?',
    error: 'Error',
    failed_sign_out: 'Failed to sign out. Please try again.',
    recently: 'Recently',
    date: 'Date',
    time: 'Time',
    enter_your_address: 'Enter your address',
    the_worker_will_come_to_this_location_to_wash_your_car: 'The worker will come to this location to wash your car',
    select_time: 'Select time',
    select_vehicle_type: 'Select vehicle type',
    any_special_instructions_or_requests: 'Any special instructions or requests?',
    missing_fields: 'Missing fields',
    please_complete: 'Please complete',
    worker_not_found: 'Worker not found',
    please_select_worker_again: 'Please go back and select a worker again.',
    // Booking Confirmation
    booking_confirmed: 'Booking Confirmed!',
    scheduled_message: 'Your car wash service has been scheduled',
    booking_id: 'Booking ID',
    your_car_washer: 'Your Car Washer',
    professional_car_washer: 'Professional Car Washer',
    confirmed: 'Confirmed',
    booking_details: 'Booking Details',
    service_location: 'Service Location',
    date_time: 'Date & Time',
    at: 'at',
    vehicle_type: 'Vehicle Type',
    payment_method: 'Payment Method',
    cash_on_delivery: 'Cash on Delivery',
    additional_notes: 'Additional Notes',
    total_amount: 'Total Amount',
    to_be_paid_upon_completion: 'To be paid upon service completion',
    important_information: 'Important Information',
    info_line_1: '• The worker will arrive at your location 5-10 minutes before the scheduled time',
    info_line_2: '• Please ensure water access is available at the service location',
    info_line_3: '• Payment is due upon completion of the service',
    info_line_4: '• You can contact the worker directly if needed',
    view_my_bookings: 'View My Bookings',
    back_to_home: 'Back to Home',
    // Bookings screen
    my_bookings: 'My Bookings',
    tab_all: 'All',
    tab_upcoming: 'Upcoming',
    tab_active: 'Active',
    tab_completed: 'Completed',
    no_bookings_found: 'No bookings found',
    no_bookings_yet: "You haven't made any bookings yet",
    no_status_bookings: 'No {status} bookings at the moment',
    book_a_service: 'Book a Service',
    booked_on: 'Booked on',
    call: 'Call',
    chat: 'Chat',
    rate_service: 'Rate Service',
    status_pending: 'Pending',
    status_confirmed: 'Confirmed',
    status_in_progress: 'In Progress',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    // Review Screen
    how_was_service: 'How was your service?',
    tap_stars_to_rate: 'Tap the stars to rate your experience',
    excellent: 'Excellent!',
    very_good: 'Very Good!',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    what_went_well: 'What went well?',
    what_went_wrong: 'What went wrong?',
    select_all_apply: 'Select all that apply (optional)',
    write_review: 'Write a Review',
    share_experience: 'Share more about your experience (optional)',
    review_placeholder: 'Tell us about your experience...',
    characters: 'characters',
    review_tips: 'Review Tips',
    tip_specific: 'Be specific about what you liked or disliked',
    tip_constructive: 'Keep feedback constructive and respectful',
    tip_helpful: 'Your review helps others make informed decisions',
    submitting: 'Submitting...',
    submit_review: 'Submit Review',
    review_submitted: 'Review Submitted',
    thank_you_feedback: 'Thank you for your feedback!',
    booking: 'Booking',
    // Review Tags - Positive
    tag_professional: 'Professional',
    tag_on_time: 'On Time',
    tag_thorough: 'Thorough',
    tag_friendly: 'Friendly',
    tag_quality: 'Great Quality',
    tag_value: 'Good Value',
    // Review Tags - Negative
    tag_late: 'Late Arrival',
    tag_rushed: 'Rushed Job',
    tag_incomplete: 'Incomplete',
    tag_unprofessional: 'Unprofessional',
    tag_expensive: 'Overpriced',
    tag_damage: 'Caused Damage',
    // Login Screen
    welcome_back: 'Welcome Back',
    sign_in_to_book: 'Sign in to book your car wash service',
    enter_your_email: 'Enter your email',
    enter_your_password: 'Enter your password',
    signing_in: 'Signing in...',
    dont_have_account: "Don't have an account?",
    login_failed: 'Login failed',
    check_credentials: 'Please check your credentials and try again.',
    // Signup Screen
    join_us_to_book: 'Join us to book professional car wash services',
    enter_full_name: 'Enter your full name',
    enter_email: 'Enter your email',
    create_password: 'Create a password',
    confirm_your_password: 'Confirm your password',
    please_confirm_password: 'Please confirm your password',
    i_agree_to: 'I agree to the',
    creating_account: 'Creating account...',
    already_have_account: 'Already have an account?',
    passwords_dont_match: "Passwords don't match",
    passwords_must_match: 'Please make sure both passwords are identical.',
    terms_not_accepted: 'Terms not accepted',
    agree_to_terms: 'Please agree to the terms and conditions to continue.',
    signup_failed: 'Signup failed',
    verify_your_email: 'Verify your email',
    verification_email_sent: 'We sent a verification link to {email}.\nOpen your email, confirm your account, then log in.',
    email_already_registered: 'This email is already registered. Please sign in or use a different email.',
    invalid_email: 'Please enter a valid email address.',
    weak_password: 'Your password does not meet the requirements.',
    // Services
    services_title: 'Services',
    services_subtitle: 'Choose a service that fits your car',
    view_details: 'View details',
    service_basic_title: 'Basic Wash',
    service_basic_desc: 'Exterior wash and dry',
    service_deluxe_title: 'Deluxe Wash',
    service_deluxe_desc: 'Exterior + interior clean',
    service_deep_title: 'Deep Clean',
    service_deep_desc: 'Full detailing in/out',
    service_interior_title: 'Interior Detail',
    service_interior_desc: 'Vacuum and interior detail',
    service_pro_title: 'Pro Package',
    service_pro_desc: 'Rinse, wax, and shine',
    // Service Detail
    service_not_found: 'Service not found.',
    go_back: 'Go back',
    whats_included: 'What’s included',
    include_line_1: '• High-pressure rinse',
    include_line_2: '• pH-neutral shampoo',
    include_line_3: '• Soft microfiber hand wash and dry',
    include_line_4: '• Windows and mirrors cleaning',
    include_line_5: '• Tyre shine and exterior finishing',
    notes: 'Notes',
    notes_body: 'Duration depends on vehicle size and condition. Prices may vary by provider. You can select a worker from the Home map and proceed to booking.',
    view_providers_for_service: 'View providers for this service',
    find_nearby_providers: 'Find nearby providers',
    // Edit Profile
    edit_profile: 'Edit Profile',
    avatar_url: 'Avatar URL',
    avatar_url_placeholder: 'https://example.com/your-photo.jpg',
    avatar_helper: 'Paste a direct image link or leave empty to use initials',
    full_name: 'Full Name',
    full_name_placeholder: 'Your full name',
    phone_placeholder: 'Your phone number',
    date_of_birth: 'Date of Birth',
    dob_placeholder: 'YYYY-MM-DD',
    dob_helper: 'Use ISO date format YYYY-MM-DD',
    gender: 'Gender',
    select_gender: 'Select gender',
    gender_male: 'Male',
    gender_female: 'Female',
    gender_other: 'Other',
    timezone: 'Timezone',
    timezone_placeholder: 'e.g. Africa/Casablanca',
    preferred_payment_method: 'Preferred Payment Method',
    select_payment_method: 'Select payment method',
    payment_cash: 'Cash',
    payment_card: 'Card',
    payment_mobile_money: 'Mobile Money',
    payment_wallet: 'Wallet',
    cancel: 'Cancel',
    profile_updated_title: 'Profile Updated',
    profile_updated_message: 'Your profile has been updated successfully.',
    something_went_wrong: 'Something went wrong. Please try again.',
    save: 'Save',
    your_profile: 'Your Profile',
    tap_to_change_photo: 'Tap to change photo',
    personal_information: 'Personal Information',
    additional_details: 'Additional Details',
    permission_required: 'Permission Required',
    camera_permission_message: 'We need access to your photo library to update your profile picture.',
    // Address Management
    add_new_address: 'Add New Address',
    no_addresses_saved: 'No addresses saved',
    add_frequently_used_addresses: 'Add your frequently used addresses for faster booking',
    add_your_first_address: 'Add Your First Address',
    default: 'Default',
    edit_address: 'Edit Address',
    delete_address: 'Delete Address',
    set_as_default: 'Set as Default',
    choose_an_action: 'Choose an action',
    are_you_sure_delete_address: 'Are you sure you want to delete {label}?',
    edit_functionality_coming_soon: 'Edit functionality for {label} will be available soon.',
    // Add Address
    add_address: 'Add Address',
    address_label: 'Address Label',
    address_label_placeholder: 'e.g. Home, Office, Gym',
    full_address: 'Full Address',
    full_address_placeholder: 'Enter complete address',
    address_type: 'Address Type',
    address_home: 'Home',
    address_work: 'Work',
    address_other: 'Other',
    set_as_default_address: 'Set as default address',
    address_added_successfully: 'Address added successfully',
    // Support & Legal
    support_legal_title: 'Support & Legal',
    contact_support: 'Contact Support',
    get_help_with_your_account: 'Get help with your account or services',
    privacy_policy: 'Privacy Policy',
    read_our_privacy_policy: 'Read our privacy policy',
    terms_of_service: 'Terms of Service',
    view_terms_and_conditions: 'View terms and conditions',
    about_app: 'About App',
    learn_more_about_app: 'Learn more about our app',
    // Help Center
    help_center_title: 'Help Center',
    frequently_asked_questions: 'Frequently Asked Questions',
    find_answers_to_common_questions: 'Find answers to common questions',
    contact_us: 'Contact Us',
    get_in_touch_with_support: 'Get in touch with our support team',
    report_issue: 'Report an Issue',
    report_bug_or_problem: 'Report a bug or problem',
    // Service Providers
    service_providers: 'Service Providers',
    available_workers: 'Available Workers',
    find_nearby_service_providers: 'Find nearby service providers',
    // Worker Profile
    worker_profile: 'Worker Profile',
    about_worker: 'About {name}',
    services_offered: 'Services Offered',
    reviews_and_ratings: 'Reviews & Ratings',
    contact_worker: 'Contact Worker',
    // Additional Address keys
    validation_error: 'Validation Error',
    address_label_required: 'Address label is required',
    address_required: 'Address is required',
    address_saved: 'Address Saved',
    address_saved_message: 'Your address has been saved successfully',
    failed_to_save_address: 'Failed to save address. Please try again.',
    location_permission_message: 'Location permission is required to use current location',
    location_found: 'Location Found',
    location_auto_filled: 'Address fields have been auto-filled with your current location',
    location_error: 'Location Error',
    unable_to_get_address: 'Unable to get address from current location',
    failed_to_get_location: 'Failed to get current location. Please try again.',
    location_services: 'Location Services',
    getting_location: 'Getting Location...',
    use_current_location: 'Use Current Location',
    default_address_description: 'Use this address for future bookings by default',
    city: 'City',
    postal_code: 'Postal Code',
    // Help Center keys
    getting_started: 'Getting Started',
    how_to_book_service: 'How to book a car wash service',
    finding_right_washer: 'Finding the right car washer',
    understanding_pricing: 'Understanding pricing',
    payment_methods_help: 'Payment methods',
    managing_bookings: 'Managing Bookings',
    canceling_rescheduling: 'Canceling or rescheduling',
    tracking_booking: 'Tracking your booking',
    rating_reviews: 'Rating and reviews',
    booking_history: 'Booking history',
    account_settings: 'Account & Settings',
    help_creating_account: 'Creating an account',
    managing_profile: 'Managing your profile',
    notification_settings: 'Notification settings',
    privacy_security: 'Privacy and security',
    troubleshooting: 'Troubleshooting',
    app_not_working: 'App not working properly',
    payment_issues: 'Payment issues',
    worker_no_show: 'Worker didn\'t show up',
    quality_concerns: 'Quality concerns',
    live_chat: 'Live Chat',
    chat_with_support: 'Chat with our support team',
    call_us: 'Call Us',
    email_support: 'Email Support',
    emergency_contact: 'Emergency Contact',
    call_emergency_hotline: 'Call emergency hotline?',
    urgent_safety_concern: 'If you have an urgent safety concern or emergency, please contact us immediately.',
    emergency_hotline: 'Emergency Hotline',
    help_topic: 'Help Topic',
    information_about: 'Information about: {item}',
    feature_available_soon: 'This feature will be available soon with detailed help content.',
    chat_feature_soon: 'Chat feature will be available soon',
    // Worker Detail Screen
    experience: 'Experience',
    starting_price: 'Starting Price',
    schedule_later: 'Schedule Later',
  },
  fr: {
    settings: 'Paramètres',
    home: 'Accueil',
    messaging: 'Messagerie',
    store: 'Boutique',
    dashboard: 'Tableau de bord',
    menu: 'Menu',
    account: 'Compte',
    preferences: 'Préférences',
    support_legal: 'Support & Légal',
    language: 'Langue',
    theme: 'Thème',
    help_center: 'Centre d\'aide',
    choose_language: 'Choisissez votre langue préférée',
    english: 'Anglais',
    french: 'Français',
    confirm_booking: 'Confirmer la réservation',
    update_personal_info: 'Mettre à jour vos informations personnelles',
    manage_addresses: 'Gérer les adresses',
    add_edit_locations: 'Ajouter ou modifier vos lieux enregistrés',
    payment_methods: 'Moyens de paiement',
    manage_payment_options: 'Gérer vos options de paiement',
    choose_app_appearance: 'Choisissez l\'apparence de l\'application',
    help_privacy_terms_about: 'Aide, Confidentialité, Conditions, À propos',
    select_date: 'Sélectionner une date',
    back: 'Retour',
    is_coming_soon: 'arrive bientôt',
    we_are_working_to_bring: 'Nous travaillons dur pour vous apporter',
    to_you_stay_tuned: 'bientôt. Restez à l\'écoute !',
    close: 'Fermer',
    search_placeholder: 'Rechercher des services de lavage auto…',
    book_now: 'Réserver',
    book: 'Réserver',
    km_away: 'km',
    location_permission: 'Autorisation de localisation',
    permission_denied_msg: 'Permission refusée. Utilisation du centre-ville par défaut.',
    profile: 'Profil',
    welcome_guest: 'Bienvenue, Invité !\n',
    guest_prompt: 'Connectez-vous ou créez un compte pour accéder à votre profil et à votre historique de réservations',
    sign_in: 'Se connecter',
    create_account: 'Créer un compte',
    service_provider: 'Prestataire',
    customer: 'Client',
    member_since: 'Membre depuis',
    your_stats: 'Vos statistiques',
    rating_label: 'Note',
    jobs_done: 'Travaux effectués',
    contact_information: 'Informations de contact',
    email: 'E-mail',
    phone: 'Téléphone',
    location: 'Emplacement',
    account_label: 'Compte',
    change_password: 'Changer le mot de passe',
    worker_dashboard: 'Tableau de bord prestataire',
    sign_out: 'Se déconnecter',
    sign_out_confirm_title: 'Déconnexion',
    sign_out_confirm_message: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    error: 'Erreur',
    failed_sign_out: 'Échec de la déconnexion. Veuillez réessayer.',
    recently: 'Récemment',
    date: 'Date',
    time: 'Heure',
    enter_your_address: 'Entrez votre adresse',
    the_worker_will_come_to_this_location_to_wash_your_car: "Le prestataire viendra à cet endroit pour nettoyer votre voiture",
    select_time: 'Sélectionner une heure',
    select_vehicle_type: 'Sélectionner un type de véhicule',
    any_special_instructions_or_requests: 'Des instructions ou demandes particulières ?',
    missing_fields: 'Champs manquants',
    please_complete: 'Veuillez compléter',
    worker_not_found: 'Prestataire introuvable',
    please_select_worker_again: 'Veuillez revenir en arrière et sélectionner un prestataire à nouveau.',
    // Booking Confirmation
    booking_confirmed: 'Réservation confirmée !',
    scheduled_message: 'Votre lavage de voiture a été planifié',
    booking_id: 'ID de réservation',
    your_car_washer: 'Votre laveur de voitures',
    professional_car_washer: 'Laveur de voitures professionnel',
    confirmed: 'Confirmée',
    booking_details: 'Détails de la réservation',
    service_location: 'Lieu du service',
    date_time: 'Date et heure',
    at: 'à',
    vehicle_type: 'Type de véhicule',
    payment_method: 'Moyen de paiement',
    cash_on_delivery: 'Paiement à la livraison',
    additional_notes: 'Notes supplémentaires',
    total_amount: 'Montant total',
    to_be_paid_upon_completion: 'À payer à la fin du service',
    important_information: 'Informations importantes',
    info_line_1: '• Le laveur arrivera 5 à 10 minutes avant l\'heure prévue',
    info_line_2: '• Assurez-vous qu\'un accès à l\'eau est disponible sur place',
    info_line_3: '• Le paiement est dû à la fin du service',
    info_line_4: '• Vous pouvez contacter le laveur directement si nécessaire',
    view_my_bookings: 'Voir mes réservations',
    back_to_home: 'Retour à l\'accueil',
    // Bookings screen
    my_bookings: 'Mes réservations',
    tab_all: 'Tout',
    tab_upcoming: 'À venir',
    tab_active: 'En cours',
    tab_completed: 'Terminées',
    no_bookings_found: 'Aucune réservation trouvée',
    no_bookings_yet: "Vous n\'avez pas encore effectué de réservation",
    no_status_bookings: 'Aucune réservation {status} pour le moment',
    book_a_service: 'Réserver un service',
    booked_on: 'Réservé le',
    call: 'Appeler',
    chat: 'Discuter',
    rate_service: 'Évaluer le service',
    status_pending: 'En attente',
    status_confirmed: 'Confirmée',
    status_in_progress: 'En cours',
    status_completed: 'Terminée',
    status_cancelled: 'Annulée',
    // Review Screen
    how_was_service: 'Comment était votre service ?',
    tap_stars_to_rate: 'Appuyez sur les étoiles pour évaluer votre expérience',
    excellent: 'Excellent !',
    very_good: 'Très bien !',
    good: 'Bien',
    fair: 'Passable',
    poor: 'Médiocre',
    what_went_well: 'Qu\'est-ce qui s\'est bien passé ?',
    what_went_wrong: 'Qu\'est-ce qui n\'a pas fonctionné ?',
    select_all_apply: 'Sélectionnez tout ce qui s\'applique (optionnel)',
    write_review: 'Écrire un avis',
    share_experience: 'Partagez-en plus sur votre expérience (optionnel)',
    review_placeholder: 'Parlez-nous de votre expérience...',
    characters: 'caractères',
    review_tips: 'Conseils pour l\'avis',
    tip_specific: 'Soyez précis sur ce que vous avez aimé ou pas',
    tip_constructive: 'Gardez vos commentaires constructifs et respectueux',
    tip_helpful: 'Votre avis aide les autres à prendre des décisions éclairées',
    submitting: 'Envoi en cours...',
    submit_review: 'Soumettre l\'avis',
    review_submitted: 'Avis soumis',
    thank_you_feedback: 'Merci pour votre retour !',
    booking: 'Réservation',
    // Review Tags - Positive
    tag_professional: 'Professionnel',
    tag_on_time: 'À l\'heure',
    tag_thorough: 'Minutieux',
    tag_friendly: 'Sympathique',
    tag_quality: 'Excellente qualité',
    tag_value: 'Bon rapport qualité-prix',
    // Review Tags - Negative
    tag_late: 'Arrivée tardive',
    tag_rushed: 'Travail bâclé',
    tag_incomplete: 'Incomplet',
    tag_unprofessional: 'Peu professionnel',
    tag_expensive: 'Trop cher',
    tag_damage: 'A causé des dommages',
    // Login Screen
    welcome_back: 'Bienvenue',
    sign_in_to_book: 'Connectez-vous pour réserver votre service de lavage auto',
    enter_your_email: 'Entrez votre email',
    enter_your_password: 'Entrez votre mot de passe',
    signing_in: 'Connexion en cours...',
    dont_have_account: "Vous n'avez pas de compte ?",
    login_failed: 'Échec de la connexion',
    check_credentials: 'Veuillez vérifier vos identifiants et réessayer.',
    // Signup Screen
    join_us_to_book: 'Rejoignez-nous pour réserver des services professionnels de lavage auto',
    enter_full_name: 'Entrez votre nom complet',
    enter_email: 'Entrez votre email',
    create_password: 'Créez un mot de passe',
    confirm_your_password: 'Confirmez votre mot de passe',
    please_confirm_password: 'Veuillez confirmer votre mot de passe',
    i_agree_to: 'J\'accepte les',
    creating_account: 'Création du compte...',
    already_have_account: 'Vous avez déjà un compte ?',
    passwords_dont_match: 'Les mots de passe ne correspondent pas',
    passwords_must_match: 'Veuillez vous assurer que les deux mots de passe sont identiques.',
    terms_not_accepted: 'Conditions non acceptées',
    agree_to_terms: 'Veuillez accepter les conditions générales pour continuer.',
    signup_failed: 'Échec de l\'inscription',
    verify_your_email: 'Vérifiez votre email',
    verification_email_sent: 'Nous avons envoyé un lien de vérification à {email}.\\nOuvrez votre email, confirmez votre compte, puis connectez-vous.',
    email_already_registered: 'Cet email est déjà enregistré. Veuillez vous connecter ou utiliser un autre email.',
    invalid_email: 'Veuillez entrer une adresse email valide.',
    weak_password: 'Votre mot de passe ne répond pas aux exigences.',
    // Services
    services_title: 'Services',
    services_subtitle: 'Choisissez un service adapté à votre voiture',
    view_details: 'Voir les détails',
    service_basic_title: 'Lavage basique',
    service_basic_desc: 'Lavage extérieur et séchage',
    service_deluxe_title: 'Lavage deluxe',
    service_deluxe_desc: 'Nettoyage extérieur + intérieur',
    service_deep_title: 'Nettoyage en profondeur',
    service_deep_desc: 'Détail complet intérieur/extérieur',
    service_interior_title: 'Détail intérieur',
    service_interior_desc: 'Aspiration et nettoyage intérieur',
    service_pro_title: 'Pack Pro',
    service_pro_desc: 'Rinçage, cire et polissage',
    // Service Detail
    service_not_found: 'Service introuvable.',
    go_back: 'Retour',
    whats_included: 'Ce qui est inclus',
    include_line_1: '• Rinçage haute pression',
    include_line_2: '• Shampoing au pH neutre',
    include_line_3: '• Lavage et séchage à la microfibre',
    include_line_4: '• Nettoyage des vitres et miroirs',
    include_line_5: '• Brillance des pneus et finition extérieure',
    notes: 'Notes',
    notes_body: 'La durée dépend de la taille et de l’état du véhicule. Les prix peuvent varier selon le prestataire. Vous pouvez sélectionner un travailleur depuis la carte d’accueil et procéder à la réservation.',
    view_providers_for_service: 'Voir les prestataires pour ce service',
    find_nearby_providers: 'Trouver des prestataires à proximité',
    avatar_url: 'URL de l’avatar',
    avatar_url_placeholder: 'https://exemple.com/votre-photo.jpg',
    avatar_helper: 'Collez un lien d’image direct ou laissez vide pour utiliser les initiales',
    full_name: 'Nom complet',
    full_name_placeholder: 'Votre nom complet',
    phone_placeholder: 'Votre numéro de téléphone',
    date_of_birth: 'Date de naissance',
    dob_placeholder: 'AAAA-MM-JJ',
    dob_helper: 'Utilisez le format ISO AAAA-MM-JJ',
    gender: 'Genre',
    select_gender: 'Sélectionner le genre',
    gender_male: 'Homme',
    gender_female: 'Femme',
    gender_other: 'Autre',
    timezone: 'Fuseau horaire',
    timezone_placeholder: 'ex. Africa/Casablanca',
    preferred_payment_method: 'Mode de paiement préféré',
    select_payment_method: 'Sélectionner un mode de paiement',
    payment_cash: 'Espèces',
    payment_card: 'Carte',
    payment_mobile_money: 'Mobile Money',
    payment_wallet: 'Portefeuille',
    cancel: 'Annuler',
    profile_updated_title: 'Profil mis à jour',
    profile_updated_message: 'Votre profil a été mis à jour avec succès.',
    something_went_wrong: 'Une erreur est survenue. Veuillez réessayer.',
    save: 'Enregistrer',
    your_profile: 'Votre Profil',
    tap_to_change_photo: 'Appuyez pour changer la photo',
    personal_information: 'Informations personnelles',
    additional_details: 'Détails supplémentaires',
    permission_required: 'Autorisation requise',
    camera_permission_message: 'Nous avons besoin d\'accéder à votre photothèque pour mettre à jour votre photo de profil.',
    // Address Management
    add_new_address: 'Ajouter une nouvelle adresse',
    no_addresses_saved: 'Aucune adresse enregistrée',
    add_frequently_used_addresses: 'Ajoutez vos adresses fréquemment utilisées pour une réservation plus rapide',
    add_your_first_address: 'Ajoutez votre première adresse',
    default: 'Par défaut',
    edit_address: 'Modifier l\'adresse',
    delete_address: 'Supprimer l\'adresse',
    set_as_default: 'Définir par défaut',
    choose_an_action: 'Choisissez une action',
    are_you_sure_delete_address: 'Êtes-vous sûr de vouloir supprimer {label} ?',
    edit_functionality_coming_soon: 'La fonctionnalité de modification pour {label} sera bientôt disponible.',
    // Add Address
    add_address: 'Ajouter une adresse',
    address_label: 'Libellé de l\'adresse',
    address_label_placeholder: 'ex. Maison, Bureau, Salle de sport',
    full_address: 'Adresse complète',
    full_address_placeholder: 'Entrez l\'adresse complète',
    address_type: 'Type d\'adresse',
    address_home: 'Maison',
    address_work: 'Travail',
    address_other: 'Autre',
    set_as_default_address: 'Définir comme adresse par défaut',
    address_added_successfully: 'Adresse ajoutée avec succès',
    // Support & Legal
    support_legal_title: 'Support et Légal',
    contact_support: 'Contacter le support',
    get_help_with_your_account: 'Obtenez de l\'aide avec votre compte ou vos services',
    privacy_policy: 'Politique de confidentialité',
    read_our_privacy_policy: 'Lisez notre politique de confidentialité',
    terms_of_service: 'Conditions d\'utilisation',
    view_terms_and_conditions: 'Voir les termes et conditions',
    about_app: 'À propos de l\'app',
    learn_more_about_app: 'En savoir plus sur notre application',
    // Help Center
    help_center_title: 'Centre d\'aide',
    frequently_asked_questions: 'Questions fréquemment posées',
    find_answers_to_common_questions: 'Trouvez des réponses aux questions courantes',
    contact_us: 'Nous contacter',
    get_in_touch_with_support: 'Contactez notre équipe de support',
    report_issue: 'Signaler un problème',
    report_bug_or_problem: 'Signaler un bug ou un problème',
    // Service Providers
    service_providers: 'Prestataires de services',
    available_workers: 'Travailleurs disponibles',
    find_nearby_service_providers: 'Trouvez des prestataires de services à proximité',
    // Worker Profile
    worker_profile: 'Profil du travailleur',
    about_worker: 'À propos de {name}',
    services_offered: 'Services offerts',
    reviews_and_ratings: 'Avis et évaluations',
    contact_worker: 'Contacter le travailleur',
    // Worker Detail Screen
    experience: 'Expérience',
    starting_price: 'Prix de départ',
    schedule_later: 'Programmer plus tard',
  },
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage, persist?: boolean) => Promise<void>;
  t: (key: string) => string;
  languageLabel: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const initial = (user?.profile?.language_preference as AppLanguage) || 'en';
  const [language, setLangState] = useState<AppLanguage>(initial);

  useEffect(() => {
    if (user?.profile?.language_preference && user.profile.language_preference !== language) {
      setLangState(user.profile.language_preference as AppLanguage);
    }
  }, [user?.profile?.language_preference]);

  const setLanguage = async (lang: AppLanguage, persist: boolean = true) => {
    setLangState(lang);
    if (persist && user?.id) {
      try {
        await authService.updateProfile(user.id, { language_preference: lang } as any);
      } catch (e) {
        // noop
      }
    }
  };

  const t = (key: string) => {
    const dict = dictionaries[language] || dictionaries.en;
    return dict[key] ?? key;
  };

  const languageLabel = useMemo(() => {
    const labelsInUILang: Record<AppLanguage, Record<AppLanguage, string>> = {
      en: { en: 'English', fr: 'Français' },
      fr: { en: 'Anglais', fr: 'Français' },
    };
    return labelsInUILang[language]?.[language] || 'English';
  }, [language]);

  const value: LanguageContextType = { language, setLanguage, t, languageLabel };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
