import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { authService } from '../services/auth';
import { useAuth } from './AuthContext';

export type AppLanguage = 'en' | 'fr' | 'ar';

type Dictionary = Record<string, string>;

const dictionaries: Record<AppLanguage, Dictionary> = {
  en: {
    settings: 'Settings',
    home: 'Home',
    messaging: 'Messaging',
    store: 'Store',
    dashboard: 'Dashboard',
    menu: 'Menu',
    account: 'Account',
    preferences: 'Preferences',
    support_legal: 'Support & Legal',
    language: 'Language',
    theme: 'Theme',
    help_center: 'Help Center',
    choose_language: 'Choose your preferred language',
    english: 'English',
    french: 'Français',
    arabic: 'العربية',
    save_changes: 'Save Changes',
    confirm_booking: 'Confirm Booking',
    update_personal_info: 'Update your personal information',
    manage_addresses: 'Manage Addresses',
    add_edit_locations: 'Add or edit your saved locations',
    payment_methods: 'Payment Methods',
    manage_payment_options: 'Manage your payment options',
    choose_app_appearance: 'Choose your app appearance',
    help_privacy_terms_about: 'Help, Privacy, Terms, About',
    select_date: 'Select a date',
    back: 'Back',
    is_coming_soon: 'is coming soon',
    we_are_working_to_bring: 'We are working hard to bring',
    to_you_stay_tuned: 'to you. Stay tuned!',
    close: 'Close',
    search_placeholder: 'Search for car wash services…',
    book_now: 'Book Now',
    book: 'Book',
    km_away: 'km away',
    location_permission: 'Location Permission',
    permission_denied_msg: 'Permission denied. Using default city center.',
    profile: 'Profile',
    welcome_guest: 'Welcome, Guest!\n',
    guest_prompt: 'Sign in or create an account to access your profile and booking history',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    service_provider: 'Service Provider',
    customer: 'Customer',
    member_since: 'Member since',
    your_stats: 'Your Stats',
    rating_label: 'Rating',
    jobs_done: 'Jobs Done',
    contact_information: 'Contact Information',
    email: 'Email',
    phone: 'Phone',
    location: 'Location',
    account_label: 'Account',
    change_password: 'Change Password',
    worker_dashboard: 'Worker Dashboard',
    sign_out: 'Sign Out',
    sign_out_confirm_title: 'Sign Out',
    sign_out_confirm_message: 'Are you sure you want to sign out?',
    error: 'Error',
    failed_sign_out: 'Failed to sign out. Please try again.',
    recently: 'Recently',
    date: 'Date',
    time: 'Time',
    enter_your_address: 'Enter your address',
    the_worker_will_come_to_this_location_to_wash_your_car: 'The worker will come to this location to wash your car',
    select_time: 'Select time',
    select_vehicle_type: 'Select vehicle type',
    any_special_instructions_or_requests: 'Any special instructions or requests?',
    missing_fields: 'Missing fields',
    please_complete: 'Please complete',
    worker_not_found: 'Worker not found',
    please_select_worker_again: 'Please go back and select a worker again.',
    // Booking Confirmation
    booking_confirmed: 'Booking Confirmed!',
    scheduled_message: 'Your car wash service has been scheduled',
    booking_id: 'Booking ID',
    your_car_washer: 'Your Car Washer',
    professional_car_washer: 'Professional Car Washer',
    confirmed: 'Confirmed',
    booking_details: 'Booking Details',
    service_location: 'Service Location',
    date_time: 'Date & Time',
    at: 'at',
    vehicle_type: 'Vehicle Type',
    payment_method: 'Payment Method',
    cash_on_delivery: 'Cash on Delivery',
    additional_notes: 'Additional Notes',
    total_amount: 'Total Amount',
    to_be_paid_upon_completion: 'To be paid upon service completion',
    important_information: 'Important Information',
    info_line_1: '• The worker will arrive at your location 5-10 minutes before the scheduled time',
    info_line_2: '• Please ensure water access is available at the service location',
    info_line_3: '• Payment is due upon completion of the service',
    info_line_4: '• You can contact the worker directly if needed',
    view_my_bookings: 'View My Bookings',
    back_to_home: 'Back to Home',
    // Bookings screen
    my_bookings: 'My Bookings',
    tab_all: 'All',
    tab_upcoming: 'Upcoming',
    tab_active: 'Active',
    tab_completed: 'Completed',
    no_bookings_found: 'No bookings found',
    no_bookings_yet: "You haven't made any bookings yet",
    no_status_bookings: 'No {status} bookings at the moment',
    book_a_service: 'Book a Service',
    booked_on: 'Booked on',
    call: 'Call',
    chat: 'Chat',
    rate_service: 'Rate Service',
    status_pending: 'Pending',
    status_confirmed: 'Confirmed',
    status_in_progress: 'In Progress',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    // Services
    services_title: 'Services',
    services_subtitle: 'Choose a service that fits your car',
    view_details: 'View details',
    service_basic_title: 'Basic Wash',
    service_basic_desc: 'Exterior wash and dry',
    service_deluxe_title: 'Deluxe Wash',
    service_deluxe_desc: 'Exterior + interior clean',
    service_deep_title: 'Deep Clean',
    service_deep_desc: 'Full detailing in/out',
    service_interior_title: 'Interior Detail',
    service_interior_desc: 'Vacuum and interior detail',
    service_pro_title: 'Pro Package',
    service_pro_desc: 'Rinse, wax, and shine',
    // Service Detail
    service_not_found: 'Service not found.',
    go_back: 'Go back',
    whats_included: 'What’s included',
    include_line_1: '• High-pressure rinse',
    include_line_2: '• pH-neutral shampoo',
    include_line_3: '• Soft microfiber hand wash and dry',
    include_line_4: '• Windows and mirrors cleaning',
    include_line_5: '• Tyre shine and exterior finishing',
    notes: 'Notes',
    notes_body: 'Duration depends on vehicle size and condition. Prices may vary by provider. You can select a worker from the Home map and proceed to booking.',
    view_providers_for_service: 'View providers for this service',
    find_nearby_providers: 'Find nearby providers',
    // Edit Profile
    edit_profile: 'Edit Profile',
    avatar_url: 'Avatar URL',
    avatar_url_placeholder: 'https://example.com/your-photo.jpg',
    avatar_helper: 'Paste a direct image link or leave empty to use initials',
    full_name: 'Full Name',
    full_name_placeholder: 'Your full name',
    phone_placeholder: 'Your phone number',
    date_of_birth: 'Date of Birth',
    dob_placeholder: 'YYYY-MM-DD',
    dob_helper: 'Use ISO date format YYYY-MM-DD',
    gender: 'Gender',
    select_gender: 'Select gender',
    gender_male: 'Male',
    gender_female: 'Female',
    gender_other: 'Other',
    timezone: 'Timezone',
    timezone_placeholder: 'e.g. Africa/Casablanca',
    preferred_payment_method: 'Preferred Payment Method',
    select_payment_method: 'Select payment method',
    payment_cash: 'Cash',
    payment_card: 'Card',
    payment_mobile_money: 'Mobile Money',
    payment_wallet: 'Wallet',
    cancel: 'Cancel',
    profile_updated_title: 'Profile Updated',
    profile_updated_message: 'Your profile has been updated successfully.',
    something_went_wrong: 'Something went wrong. Please try again.',
    save: 'Save',
    your_profile: 'Your Profile',
    tap_to_change_photo: 'Tap to change photo',
    personal_information: 'Personal Information',
    additional_details: 'Additional Details',
    permission_required: 'Permission Required',
    camera_permission_message: 'We need access to your photo library to update your profile picture.',
    // Address Management
    add_new_address: 'Add New Address',
    no_addresses_saved: 'No addresses saved',
    add_frequently_used_addresses: 'Add your frequently used addresses for faster booking',
    add_your_first_address: 'Add Your First Address',
    default: 'Default',
    edit_address: 'Edit Address',
    delete_address: 'Delete Address',
    set_as_default: 'Set as Default',
    choose_an_action: 'Choose an action',
    are_you_sure_delete_address: 'Are you sure you want to delete {label}?',
    edit_functionality_coming_soon: 'Edit functionality for {label} will be available soon.',
    // Add Address
    add_address: 'Add Address',
    address_label: 'Address Label',
    address_label_placeholder: 'e.g. Home, Office, Gym',
    full_address: 'Full Address',
    full_address_placeholder: 'Enter complete address',
    address_type: 'Address Type',
    address_home: 'Home',
    address_work: 'Work',
    address_other: 'Other',
    set_as_default_address: 'Set as default address',
    address_added_successfully: 'Address added successfully',
    // Support & Legal
    support_legal_title: 'Support & Legal',
    contact_support: 'Contact Support',
    get_help_with_your_account: 'Get help with your account or services',
    privacy_policy: 'Privacy Policy',
    read_our_privacy_policy: 'Read our privacy policy',
    terms_of_service: 'Terms of Service',
    view_terms_and_conditions: 'View terms and conditions',
    about_app: 'About App',
    learn_more_about_app: 'Learn more about our app',
    // Help Center
    help_center_title: 'Help Center',
    frequently_asked_questions: 'Frequently Asked Questions',
    find_answers_to_common_questions: 'Find answers to common questions',
    contact_us: 'Contact Us',
    get_in_touch_with_support: 'Get in touch with our support team',
    report_issue: 'Report an Issue',
    report_bug_or_problem: 'Report a bug or problem',
    // Service Providers
    service_providers: 'Service Providers',
    available_workers: 'Available Workers',
    find_nearby_service_providers: 'Find nearby service providers',
    // Worker Profile
    worker_profile: 'Worker Profile',
    about_worker: 'About {name}',
    services_offered: 'Services Offered',
    reviews_and_ratings: 'Reviews & Ratings',
    contact_worker: 'Contact Worker',
    // Additional Address keys
    validation_error: 'Validation Error',
    address_label_required: 'Address label is required',
    address_required: 'Address is required',
    address_saved: 'Address Saved',
    address_saved_message: 'Your address has been saved successfully',
    failed_to_save_address: 'Failed to save address. Please try again.',
    location_permission_message: 'Location permission is required to use current location',
    location_found: 'Location Found',
    location_auto_filled: 'Address fields have been auto-filled with your current location',
    location_error: 'Location Error',
    unable_to_get_address: 'Unable to get address from current location',
    failed_to_get_location: 'Failed to get current location. Please try again.',
    location_services: 'Location Services',
    getting_location: 'Getting Location...',
    use_current_location: 'Use Current Location',
    default_address_description: 'Use this address for future bookings by default',
    city: 'City',
    postal_code: 'Postal Code',
    // Help Center keys
    getting_started: 'Getting Started',
    how_to_book_service: 'How to book a car wash service',
    finding_right_washer: 'Finding the right car washer',
    understanding_pricing: 'Understanding pricing',
    payment_methods_help: 'Payment methods',
    managing_bookings: 'Managing Bookings',
    canceling_rescheduling: 'Canceling or rescheduling',
    tracking_booking: 'Tracking your booking',
    rating_reviews: 'Rating and reviews',
    booking_history: 'Booking history',
    account_settings: 'Account & Settings',
    creating_account: 'Creating an account',
    managing_profile: 'Managing your profile',
    notification_settings: 'Notification settings',
    privacy_security: 'Privacy and security',
    troubleshooting: 'Troubleshooting',
    app_not_working: 'App not working properly',
    payment_issues: 'Payment issues',
    worker_no_show: 'Worker didn\'t show up',
    quality_concerns: 'Quality concerns',
    live_chat: 'Live Chat',
    chat_with_support: 'Chat with our support team',
    call_us: 'Call Us',
    email_support: 'Email Support',
    emergency_contact: 'Emergency Contact',
    call_emergency_hotline: 'Call emergency hotline?',
    urgent_safety_concern: 'If you have an urgent safety concern or emergency, please contact us immediately.',
    emergency_hotline: 'Emergency Hotline',
    help_topic: 'Help Topic',
    information_about: 'Information about: {item}',
    feature_available_soon: 'This feature will be available soon with detailed help content.',
    chat_feature_soon: 'Chat feature will be available soon',
  },
  fr: {
    settings: 'Paramètres',
    home: 'Accueil',
    messaging: 'Messagerie',
    store: 'Boutique',
    dashboard: 'Tableau de bord',
    menu: 'Menu',
    account: 'Compte',
    preferences: 'Préférences',
    support_legal: 'Support & Légal',
    language: 'Langue',
    theme: 'Thème',
    help_center: 'Centre d\'aide',
    choose_language: 'Choisissez votre langue préférée',
    english: 'Anglais',
    french: 'Français',
    arabic: 'Arabe',
    confirm_booking: 'Confirmer la réservation',
    update_personal_info: 'Mettre à jour vos informations personnelles',
    manage_addresses: 'Gérer les adresses',
    add_edit_locations: 'Ajouter ou modifier vos lieux enregistrés',
    payment_methods: 'Moyens de paiement',
    manage_payment_options: 'Gérer vos options de paiement',
    choose_app_appearance: 'Choisissez l\'apparence de l\'application',
    help_privacy_terms_about: 'Aide, Confidentialité, Conditions, À propos',
    select_date: 'Sélectionner une date',
    back: 'Retour',
    is_coming_soon: 'arrive bientôt',
    we_are_working_to_bring: 'Nous travaillons dur pour vous apporter',
    to_you_stay_tuned: 'bientôt. Restez à l\'écoute !',
    close: 'Fermer',
    search_placeholder: 'Rechercher des services de lavage auto…',
    book_now: 'Réserver',
    book: 'Réserver',
    km_away: 'km',
    location_permission: 'Autorisation de localisation',
    permission_denied_msg: 'Permission refusée. Utilisation du centre-ville par défaut.',
    profile: 'Profil',
    welcome_guest: 'Bienvenue, Invité !\n',
    guest_prompt: 'Connectez-vous ou créez un compte pour accéder à votre profil et à votre historique de réservations',
    sign_in: 'Se connecter',
    create_account: 'Créer un compte',
    service_provider: 'Prestataire',
    customer: 'Client',
    member_since: 'Membre depuis',
    your_stats: 'Vos statistiques',
    rating_label: 'Note',
    jobs_done: 'Travaux effectués',
    contact_information: 'Informations de contact',
    email: 'E-mail',
    phone: 'Téléphone',
    location: 'Emplacement',
    account_label: 'Compte',
    change_password: 'Changer le mot de passe',
    worker_dashboard: 'Tableau de bord prestataire',
    sign_out: 'Se déconnecter',
    sign_out_confirm_title: 'Déconnexion',
    sign_out_confirm_message: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    error: 'Erreur',
    failed_sign_out: 'Échec de la déconnexion. Veuillez réessayer.',
    recently: 'Récemment',
    date: 'Date',
    time: 'Heure',
    enter_your_address: 'Entrez votre adresse',
    the_worker_will_come_to_this_location_to_wash_your_car: "Le prestataire viendra à cet endroit pour nettoyer votre voiture",
    select_time: 'Sélectionner une heure',
    select_vehicle_type: 'Sélectionner un type de véhicule',
    any_special_instructions_or_requests: 'Des instructions ou demandes particulières ?',
    missing_fields: 'Champs manquants',
    please_complete: 'Veuillez compléter',
    worker_not_found: 'Prestataire introuvable',
    please_select_worker_again: 'Veuillez revenir en arrière et sélectionner un prestataire à nouveau.',
    // Booking Confirmation
    booking_confirmed: 'Réservation confirmée !',
    scheduled_message: 'Votre lavage de voiture a été planifié',
    booking_id: 'ID de réservation',
    your_car_washer: 'Votre laveur de voitures',
    professional_car_washer: 'Laveur de voitures professionnel',
    confirmed: 'Confirmée',
    booking_details: 'Détails de la réservation',
    service_location: 'Lieu du service',
    date_time: 'Date et heure',
    at: 'à',
    vehicle_type: 'Type de véhicule',
    payment_method: 'Moyen de paiement',
    cash_on_delivery: 'Paiement à la livraison',
    additional_notes: 'Notes supplémentaires',
    total_amount: 'Montant total',
    to_be_paid_upon_completion: 'À payer à la fin du service',
    important_information: 'Informations importantes',
    info_line_1: '• Le laveur arrivera 5 à 10 minutes avant l\'heure prévue',
    info_line_2: '• Assurez-vous qu\'un accès à l\'eau est disponible sur place',
    info_line_3: '• Le paiement est dû à la fin du service',
    info_line_4: '• Vous pouvez contacter le laveur directement si nécessaire',
    view_my_bookings: 'Voir mes réservations',
    back_to_home: 'Retour à l\'accueil',
    // Bookings screen
    my_bookings: 'Mes réservations',
    tab_all: 'Tout',
    tab_upcoming: 'À venir',
    tab_active: 'En cours',
    tab_completed: 'Terminées',
    no_bookings_found: 'Aucune réservation trouvée',
    no_bookings_yet: "Vous n\'avez pas encore effectué de réservation",
    no_status_bookings: 'Aucune réservation {status} pour le moment',
    book_a_service: 'Réserver un service',
    booked_on: 'Réservé le',
    call: 'Appeler',
    chat: 'Discuter',
    rate_service: 'Évaluer le service',
    status_pending: 'En attente',
    status_confirmed: 'Confirmée',
    status_in_progress: 'En cours',
    status_completed: 'Terminée',
    status_cancelled: 'Annulée',
    // Services
    services_title: 'Services',
    services_subtitle: 'Choisissez un service adapté à votre voiture',
    view_details: 'Voir les détails',
    service_basic_title: 'Lavage basique',
    service_basic_desc: 'Lavage extérieur et séchage',
    service_deluxe_title: 'Lavage deluxe',
    service_deluxe_desc: 'Nettoyage extérieur + intérieur',
    service_deep_title: 'Nettoyage en profondeur',
    service_deep_desc: 'Détail complet intérieur/extérieur',
    service_interior_title: 'Détail intérieur',
    service_interior_desc: 'Aspiration et nettoyage intérieur',
    service_pro_title: 'Pack Pro',
    service_pro_desc: 'Rinçage, cire et polissage',
    // Service Detail
    service_not_found: 'Service introuvable.',
    go_back: 'Retour',
    whats_included: 'Ce qui est inclus',
    include_line_1: '• Rinçage haute pression',
    include_line_2: '• Shampoing au pH neutre',
    include_line_3: '• Lavage et séchage à la microfibre',
    include_line_4: '• Nettoyage des vitres et miroirs',
    include_line_5: '• Brillance des pneus et finition extérieure',
    notes: 'Notes',
    notes_body: 'La durée dépend de la taille et de l’état du véhicule. Les prix peuvent varier selon le prestataire. Vous pouvez sélectionner un travailleur depuis la carte d’accueil et procéder à la réservation.',
    view_providers_for_service: 'Voir les prestataires pour ce service',
    find_nearby_providers: 'Trouver des prestataires à proximité',
    avatar_url: 'URL de l’avatar',
    avatar_url_placeholder: 'https://exemple.com/votre-photo.jpg',
    avatar_helper: 'Collez un lien d’image direct ou laissez vide pour utiliser les initiales',
    full_name: 'Nom complet',
    full_name_placeholder: 'Votre nom complet',
    phone_placeholder: 'Votre numéro de téléphone',
    date_of_birth: 'Date de naissance',
    dob_placeholder: 'AAAA-MM-JJ',
    dob_helper: 'Utilisez le format ISO AAAA-MM-JJ',
    gender: 'Genre',
    select_gender: 'Sélectionner le genre',
    gender_male: 'Homme',
    gender_female: 'Femme',
    gender_other: 'Autre',
    timezone: 'Fuseau horaire',
    timezone_placeholder: 'ex. Africa/Casablanca',
    preferred_payment_method: 'Mode de paiement préféré',
    select_payment_method: 'Sélectionner un mode de paiement',
    payment_cash: 'Espèces',
    payment_card: 'Carte',
    payment_mobile_money: 'Mobile Money',
    payment_wallet: 'Portefeuille',
    cancel: 'Annuler',
    profile_updated_title: 'Profil mis à jour',
    profile_updated_message: 'Votre profil a été mis à jour avec succès.',
    something_went_wrong: 'Une erreur est survenue. Veuillez réessayer.',
    save: 'Enregistrer',
    your_profile: 'Votre Profil',
    tap_to_change_photo: 'Appuyez pour changer la photo',
    personal_information: 'Informations personnelles',
    additional_details: 'Détails supplémentaires',
    permission_required: 'Autorisation requise',
    camera_permission_message: 'Nous avons besoin d\'accéder à votre photothèque pour mettre à jour votre photo de profil.',
    // Address Management
    add_new_address: 'Ajouter une nouvelle adresse',
    no_addresses_saved: 'Aucune adresse enregistrée',
    add_frequently_used_addresses: 'Ajoutez vos adresses fréquemment utilisées pour une réservation plus rapide',
    add_your_first_address: 'Ajoutez votre première adresse',
    default: 'Par défaut',
    edit_address: 'Modifier l\'adresse',
    delete_address: 'Supprimer l\'adresse',
    set_as_default: 'Définir par défaut',
    choose_an_action: 'Choisissez une action',
    are_you_sure_delete_address: 'Êtes-vous sûr de vouloir supprimer {label} ?',
    edit_functionality_coming_soon: 'La fonctionnalité de modification pour {label} sera bientôt disponible.',
    // Add Address
    add_address: 'Ajouter une adresse',
    address_label: 'Libellé de l\'adresse',
    address_label_placeholder: 'ex. Maison, Bureau, Salle de sport',
    full_address: 'Adresse complète',
    full_address_placeholder: 'Entrez l\'adresse complète',
    address_type: 'Type d\'adresse',
    address_home: 'Maison',
    address_work: 'Travail',
    address_other: 'Autre',
    set_as_default_address: 'Définir comme adresse par défaut',
    address_added_successfully: 'Adresse ajoutée avec succès',
    // Support & Legal
    support_legal_title: 'Support et Légal',
    contact_support: 'Contacter le support',
    get_help_with_your_account: 'Obtenez de l\'aide avec votre compte ou vos services',
    privacy_policy: 'Politique de confidentialité',
    read_our_privacy_policy: 'Lisez notre politique de confidentialité',
    terms_of_service: 'Conditions d\'utilisation',
    view_terms_and_conditions: 'Voir les termes et conditions',
    about_app: 'À propos de l\'app',
    learn_more_about_app: 'En savoir plus sur notre application',
    // Help Center
    help_center_title: 'Centre d\'aide',
    frequently_asked_questions: 'Questions fréquemment posées',
    find_answers_to_common_questions: 'Trouvez des réponses aux questions courantes',
    contact_us: 'Nous contacter',
    get_in_touch_with_support: 'Contactez notre équipe de support',
    report_issue: 'Signaler un problème',
    report_bug_or_problem: 'Signaler un bug ou un problème',
    // Service Providers
    service_providers: 'Prestataires de services',
    available_workers: 'Travailleurs disponibles',
    find_nearby_service_providers: 'Trouvez des prestataires de services à proximité',
    // Worker Profile
    worker_profile: 'Profil du travailleur',
    about_worker: 'À propos de {name}',
    services_offered: 'Services offerts',
    reviews_and_ratings: 'Avis et évaluations',
    contact_worker: 'Contacter le travailleur',
  },
  ar: {
    settings: 'الإعدادات',
    home: 'الرئيسية',
    messaging: 'الرسائل',
    store: 'المتجر',
    dashboard: 'لوحة التحكم',
    menu: 'القائمة',
    account: 'الحساب',
    preferences: 'التفضيلات',
    support_legal: 'الدعم والقانون',
    language: 'اللغة',
    theme: 'السمة',
    help_center: 'مركز المساعدة',
    choose_language: 'اختر لغتك المفضلة',
    english: 'الإنجليزية',
    french: 'الفرنسية',
    arabic: 'العربية',
    confirm_booking: 'تأكيد الحجز',
    update_personal_info: 'تحديث معلوماتك الشخصية',
    manage_addresses: 'إدارة العناوين',
    add_edit_locations: 'إضافة أو تعديل المواقع المحفوظة',
    payment_methods: 'طرق الدفع',
    manage_payment_options: 'إدارة خيارات الدفع',
    choose_app_appearance: 'اختر مظهر التطبيق',
    help_privacy_terms_about: 'المساعدة، الخصوصية، الشروط، حول',
    select_date: 'اختر تاريخًا',
    back: 'رجوع',
    is_coming_soon: 'قريبًا',
    we_are_working_to_bring: 'نعمل بجد لتقديم',
    to_you_stay_tuned: 'إليك. ترقبوا!',
    close: 'إغلاق',
    search_placeholder: 'ابحث عن خدمات غسيل السيارات…',
    book_now: 'احجز الآن',
    book: 'احجز',
    km_away: 'كم بعيد',
    location_permission: 'إذن الموقع',
    permission_denied_msg: 'تم رفض الإذن. سيتم استخدام مركز المدينة الافتراضي.',
    profile: 'الملف الشخصي',
    welcome_guest: 'مرحبًا، زائر!\n',
    guest_prompt: 'سجل الدخول أو أنشئ حسابًا للوصول إلى ملفك وتاريخ الحجوزات',
    sign_in: 'تسجيل الدخول',
    create_account: 'إنشاء حساب',
    service_provider: 'مقدم خدمة',
    customer: 'عميل',
    member_since: 'عضو منذ',
    your_stats: 'إحصاءاتك',
    rating_label: 'التقييم',
    jobs_done: 'الأعمال المنجزة',
    contact_information: 'معلومات الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    location: 'الموقع',
    account_label: 'الحساب',
    change_password: 'تغيير كلمة المرور',
    worker_dashboard: 'لوحة تحكم العامل',
    sign_out: 'تسجيل الخروج',
    sign_out_confirm_title: 'تسجيل الخروج',
    sign_out_confirm_message: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    error: 'خطأ',
    failed_sign_out: 'فشل تسجيل الخروج. حاول مرة أخرى.',
    recently: 'مؤخرًا',
    date: 'التاريخ',
    time: 'الوقت',
    enter_your_address: 'أدخل عنوانك',
    the_worker_will_come_to_this_location_to_wash_your_car: 'سيأتي العامل إلى هذا الموقع لغسل سيارتك',
    select_time: 'اختر الوقت',
    select_vehicle_type: 'اختر نوع المركبة',
    any_special_instructions_or_requests: 'هل لديك أي تعليمات أو طلبات خاصة؟',
    missing_fields: 'حقول مفقودة',
    please_complete: 'يرجى إكمال',
    worker_not_found: 'العامل غير موجود',
    please_select_worker_again: 'يرجى الرجوع للخلف واختيار عامل مرة أخرى.',
    // Booking Confirmation
    booking_confirmed: 'تم تأكيد الحجز!',
    scheduled_message: 'تم تحديد خدمة غسيل سيارتك',
    booking_id: 'رقم الحجز',
    your_car_washer: 'عامل الغسيل الخاص بك',
    professional_car_washer: 'عامل غسيل سيارات محترف',
    confirmed: 'مؤكد',
    booking_details: 'تفاصيل الحجز',
    service_location: 'موقع الخدمة',
    date_time: 'التاريخ والوقت',
    at: 'في',
    vehicle_type: 'نوع المركبة',
    payment_method: 'طريقة الدفع',
    cash_on_delivery: 'الدفع عند التسليم',
    additional_notes: 'ملاحظات إضافية',
    total_amount: 'المبلغ الإجمالي',
    to_be_paid_upon_completion: 'يتم الدفع عند إتمام الخدمة',
    important_information: 'معلومات مهمة',
    info_line_1: '• سيصل العامل إلى موقعك قبل 5-10 دقائق من الوقت المحدد',
    info_line_2: '• يرجى التأكد من توفر الوصول إلى الماء في موقع الخدمة',
    info_line_3: '• يتم الدفع عند اكتمال الخدمة',
    info_line_4: '• يمكنك التواصل مع العامل مباشرة إذا لزم الأمر',
    view_my_bookings: 'عرض حجوزاتي',
    back_to_home: 'العودة إلى الصفحة الرئيسية',
    // Bookings screen
    my_bookings: 'حجوزاتي',
    tab_all: 'الكل',
    tab_upcoming: 'القادمة',
    tab_active: 'النشطة',
    tab_completed: 'المكتملة',
    no_bookings_found: 'لا توجد حجوزات',
    no_bookings_yet: 'لم تقم بأي حجوزات بعد',
    no_status_bookings: 'لا توجد حجوزات {status} في الوقت الحالي',
    book_a_service: 'احجز خدمة',
    booked_on: 'تم الحجز في',
    call: 'اتصال',
    chat: 'دردشة',
    rate_service: 'قيّم الخدمة',
    status_pending: 'قيد الانتظار',
    status_confirmed: 'مؤكد',
    status_in_progress: 'قيد التنفيذ',
    status_completed: 'مكتمل',
    status_cancelled: 'ملغى',
    // Services
    services_title: 'الخدمات',
    services_subtitle: 'اختر خدمة تناسب سيارتك',
    view_details: 'عرض التفاصيل',
    service_basic_title: 'غسيل أساسي',
    service_basic_desc: 'غسيل خارجي وتجفيف',
    service_deluxe_title: 'غسيل ديلوكس',
    service_deluxe_desc: 'تنظيف خارجي + داخلي',
    service_deep_title: 'تنظيف عميق',
    service_deep_desc: 'تلميع كامل داخلي/خارجي',
    service_interior_title: 'تفاصيل داخلية',
    service_interior_desc: 'تفريغ وتنظيف داخلي',
    service_pro_title: 'باقة احترافية',
    service_pro_desc: 'شطف، تلميع، ولمعان',
    // Service Detail
    service_not_found: 'الخدمة غير موجودة.',
    go_back: 'رجوع',
    whats_included: 'ما الذي يتضمنه',
    include_line_1: '• شطف عالي الضغط',
    include_line_2: '• شامبو ذو درجة حموضة متعادلة',
    include_line_3: '• غسل وتجفيف بقطعة ميكروفايبر ناعمة',
    include_line_4: '• تنظيف النوافذ والمرايا',
    include_line_5: '• تلميع الإطارات وإنهاء خارجي',
    notes: 'ملاحظات',
    notes_body: 'المدة تعتمد على حجم المركبة وحالتها. قد تختلف الأسعار حسب المزود. يمكنك اختيار عامل من خريطة الرئيسية ومتابعة الحجز.',
    view_providers_for_service: 'عرض مقدمي الخدمة لهذا العرض',
    find_nearby_providers: 'اعثر على مقدمي خدمة قريبين',
    // Edit Profile
    edit_profile: 'تعديل الملف الشخصي',
    avatar_url: 'رابط الصورة (Avatar URL)',
    avatar_url_placeholder: 'https://example.com/your-photo.jpg',
    avatar_helper: 'ألصق رابط صورة مباشر أو اتركه فارغًا لاستخدام الأحرف الأولى',
    full_name: 'الاسم الكامل',
    full_name_placeholder: 'اسمك الكامل',
    phone_placeholder: 'رقم هاتفك',
    date_of_birth: 'تاريخ الميلاد',
    dob_placeholder: 'YYYY-MM-DD',
    dob_helper: 'استخدم تنسيق التاريخ ISO YYYY-MM-DD',
    gender: 'النوع',
    select_gender: 'اختر النوع',
    gender_male: 'ذكر',
    gender_female: 'أنثى',
    gender_other: 'آخر',
    timezone: 'المنطقة الزمنية',
    timezone_placeholder: 'مثال: Africa/Casablanca',
    preferred_payment_method: 'طريقة الدفع المفضلة',
    select_payment_method: 'اختر طريقة الدفع',
    payment_cash: 'نقدًا',
    payment_card: 'بطاقة',
    payment_mobile_money: 'محفظة هاتف',
    payment_wallet: 'محفظة',
    cancel: 'إلغاء',
    save_changes: 'حفظ التغييرات',
    profile_updated_title: 'تم تحديث الملف الشخصي',
    profile_updated_message: 'تم تحديث ملفك الشخصي بنجاح.',
    something_went_wrong: 'حدث خطأ ما. حاول مرة أخرى.',
    save: 'حفظ',
    your_profile: 'ملفك الشخصي',
    tap_to_change_photo: 'اضغط لتغيير الصورة',
    personal_information: 'المعلومات الشخصية',
    additional_details: 'تفاصيل إضافية',
    permission_required: 'إذن مطلوب',
    camera_permission_message: 'نحتاج إلى الوصول إلى مكتبة الصور لتحديث صورة ملفك الشخصي.',
    // Address Management
    add_new_address: 'إضافة عنوان جديد',
    no_addresses_saved: 'لا توجد عناوين محفوظة',
    add_frequently_used_addresses: 'أضف عناوينك المستخدمة بكثرة للحجز بشكل أسرع',
    add_your_first_address: 'أضف عنوانك الأول',
    default: 'افتراضي',
    edit_address: 'تعديل العنوان',
    delete_address: 'حذف العنوان',
    set_as_default: 'تعيين كافتراضي',
    choose_an_action: 'اختر إجراءً',
    are_you_sure_delete_address: 'هل أنت متأكد أنك تريد حذف {label}؟',
    edit_functionality_coming_soon: 'وظيفة التعديل لـ {label} ستكون متاحة قريباً.',
    // Add Address
    add_address: 'إضافة عنوان',
    address_label: 'تسمية العنوان',
    address_label_placeholder: 'مثل: المنزل، المكتب، الصالة الرياضية',
    full_address: 'العنوان الكامل',
    full_address_placeholder: 'أدخل العنوان الكامل',
    address_type: 'نوع العنوان',
    address_home: 'المنزل',
    address_work: 'العمل',
    address_other: 'أخرى',
    set_as_default_address: 'تعيين كعنوان افتراضي',
    address_added_successfully: 'تم إضافة العنوان بنجاح',
    // Support & Legal
    support_legal_title: 'الدعم والقانون',
    contact_support: 'اتصل بالدعم',
    get_help_with_your_account: 'احصل على مساعدة بحسابك أو خدماتك',
    privacy_policy: 'سياسة الخصوصية',
    read_our_privacy_policy: 'اقرأ سياسة الخصوصية الخاصة بنا',
    terms_of_service: 'شروط الخدمة',
    view_terms_and_conditions: 'عرض الشروط والأحكام',
    about_app: 'حول التطبيق',
    learn_more_about_app: 'تعرف على المزيد حول تطبيقنا',
    // Help Center
    help_center_title: 'مركز المساعدة',
    frequently_asked_questions: 'الأسئلة الشائعة',
    find_answers_to_common_questions: 'اعثر على إجابات للأسئلة الشائعة',
    contact_us: 'اتصل بنا',
    get_in_touch_with_support: 'تواصل مع فريق الدعم لدينا',
    report_issue: 'الإبلاغ عن مشكلة',
    report_bug_or_problem: 'الإبلاغ عن خطأ أو مشكلة',
    // Service Providers
    service_providers: 'مقدمو الخدمات',
    available_workers: 'العمال المتاحون',
    find_nearby_service_providers: 'اعثر على مقدمي خدمات قريبين',
    // Worker Profile
    worker_profile: 'ملف العامل الشخصي',
    about_worker: 'حول {name}',
    services_offered: 'الخدمات المقدمة',
    reviews_and_ratings: 'المراجعات والتقييمات',
    contact_worker: 'اتصل بالعامل',
  },
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage, persist?: boolean) => Promise<void>;
  t: (key: string) => string;
  languageLabel: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const initial = (user?.profile?.language_preference as AppLanguage) || 'en';
  const [language, setLangState] = useState<AppLanguage>(initial);

  useEffect(() => {
    if (user?.profile?.language_preference && user.profile.language_preference !== language) {
      setLangState(user.profile.language_preference as AppLanguage);
    }
  }, [user?.profile?.language_preference]);

  const setLanguage = async (lang: AppLanguage, persist: boolean = true) => {
    setLangState(lang);
    if (persist && user?.id) {
      try {
        await authService.updateProfile(user.id, { language_preference: lang } as any);
      } catch (e) {
        // noop
      }
    }
  };

  const t = (key: string) => {
    const dict = dictionaries[language] || dictionaries.en;
    return dict[key] ?? key;
  };

  const languageLabel = useMemo(() => {
    const map: Record<AppLanguage, string> = { en: dictionaries[language].english, fr: dictionaries[language].french, ar: dictionaries[language].arabic } as any;
    // Always show label in the current UI language
    const labelsInUILang = {
      en: { en: 'English', fr: 'Français', ar: 'العربية' },
      fr: { en: 'Anglais', fr: 'Français', ar: 'Arabe' },
      ar: { en: 'الإنجليزية', fr: 'الفرنسية', ar: 'العربية' },
    } as const;
    return labelsInUILang[language][language];
  }, [language]);

  const value: LanguageContextType = { language, setLanguage, t, languageLabel };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
